### ISSUE TITLE
Mankind 2.0: Raising awareness of the impact of technology on our society

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#1]
This issue proposes a campaign theme, named 'Mankind 2.0'.

The idea was first posed by [Georges](https://community.humanetech.com/u/georges/summary) in [Producing short dramatic videos to raise awareness](https://community.humanetech.com/t/producing-short-dramatic-videos-to-raise-awareness/2767) on the Humane Tech community forum.

As part of this theme a first campaign will be launched, called 'Reality Shock'

The definition of a **Reality Shock** is:

> _"Unsettling or jarring experience resulting from wide disparity between what was expected and what the real situation turns out to be."_ (source: [businessdictionary](http://www.businessdictionary.com/definition/reality-shock.html))

This issue is exclusively for discussing the theme. See the 'campaign'-labeled issues with 'Reality Shock' in the title for elaboration on individual campaign ideas.

**Comment by georgeshk** [comment]
# For brainstorming: Reality Shock Campaign Theme

Among other subjects to brainstorm is the campaign theme. As Borja pointed out, we need to have a consistent theme covering all videos to be produced under this campaign.

In my draft script for the first video, I proposed:

> The overarching theme of the campaign is to provoke and make people ponder the question: "Are you really comfortable with this?"

The rationale is:

- The aim of the campaign is not to "push" a certain agenda, or impose on the audience a cinematic "lecture". This would not be effective. If a viewer feels his views, thinking and beliefs are directly contradicted or challenged, his fist gut reaction will be to reject the video in its entirety, then consciously attack all its content. This marks a contrast between 1. Education and 2. Inspiration. My view is we need to get inspired before we are ready to commit to challenging our strong convictions.
- Instead, the videos aim at provoking viewers into introspection and reaching their own conclusions. They will be given facts or observations while watching the videos, but the conclusions are left to them.
- As to the question we are asking, the purpose in essence is to ask "We are all doing all these things without giving them second thoughts. Perhaps we need to take a few minutes, or much more than that, to wonder whether these are the right things to do?"

**Comment by georgeshk** [comment]
As to the Campaign Name, I am generally fine with "Reality Shock", save that perhaps it is quite explicit as to our intended purpose, so it would be less surprising for the audience who will anticipate the whole thing. I was thinking of "Mankind 2.0" as the name of the first video, but that could also be an idea for the whole campaign. Any other idea?

**Comment by georgeshk** [comment]
An attempt at the README file.

| Field | Description |
| :---: | :--- |
| `Name` | Reality Shock |
| `Summary` | Raising awareness of the impact of technology on our society by producing unsettling or jarring experiences resulting from a wide disparity between what was expected and what the real situation turns out to be. |
| `Topics` | <ul><li>Smartphone addiction</li><li>Social media addiction</li><li>Privacy</li><li>Social credits</li><li>Etc</li></ul> |
| `Objectives` | <ul><li>Shock the audience</li><li>Lead to introspection and questioning</li><li>Make the audience think and reach their own conclusions</li><li>Provoke, rather than convince</li></ul> |
| `Description` | This theme is based on the following principles:<br><br><ul><li>Not to push a certain agenda, or lecture the target audience</li><li>Instead, provoke introspection and lead the audience to reach their own conclusions as to whether they are comfortable with the impact of such and such aspect of technology on their lives</li><li>Acknowledge that we have become a very different society in a very short time and ask the question: "Should we consider this more carefully?"</li></ul> |
| `Strategy` | (optional) If there is a common strategy, outline it here |
| `Campaigns` | Hyperlinked ToC to past, ongoing and future campaigns |
| `Resources` | (optional) Links to relevant subfolders, files and external information |

**Comment by aschrijver** [comment]
Damn, I am making a mess of this thread :slightly_smiling_face: Should create new issue.

Let me address part of my feedback on **Mankind 2.0** here, then @georgeshk :

- 'Mankind 2.0' is a much broader concept than 'Reality Shock'
- I think Theme and Campaign names should be swapped
  - The theme should be 'Mankind 2.0'
  - The campaign then is 'Reality Shock'
- Makes more sense to me as the deliverables are video's that (gently) shock people into awareness

What do you think?

**Comment by georgeshk** [comment]
I am outside now but I guess should not be a problem to swap the names. So, Phone Zombies would also fall under Mankind 2.0? If confirmed, I can take care of swapping the names in relevant issues and readme files.

**Comment by aschrijver** [comment]
I am editing right now, so I better do the swapping. Have some checkins to make soon.

The Phone Zombies is part of a different theme 'Speak Easy', because the overall objective here is to change pubic consciousness by introducing new language terminology (in popular language / slang).

**Comment by georgeshk** [comment]
In that case, then ok with swapping the names, now that Phone Zombies is under a different theme, no more concerns.

**Comment by aschrijver** [comment]
I have been editing all over the place, to make things interconnect. But all folders, subfolders and README's are now there, the swapping is done. I am now cleaning the issues a bit (just changing titles)

Though it may be better if I create new ones (copies), once I have created proper issue templates. Then we'll have clean slate and I will give feedback to your great drafts (if I have any).

Agree?

**Comment by georgeshk** [comment]
Ok. Near 7pm here so will look at it tomorrow. Right now, I am more concerned about the forum... As you know, I strongly suggest labeling all campaigns under "Awareness". Advocacy is not our concern here. We are very far from being able to go there.

**Comment by georgeshk** [comment]
Good morning @schrijver

Woke up to see all the great work you did here. The whole place now seems to have found its natural order.

Note to all contributors: there has been a lot of structuring work going on here for the sake of making our collaboration super efffective (all thanks to Arnold). No need to focus on this, please go and provide your insights on the themes, campaigns and deliverables that are dear to your heart. Please also feel free to create new issues in the Issues tab to discuss any related topic, be it a new campaign or video idea, or a strategic aspect (production, financing and distribution).

**Comment by aschrijver** [comment]
Thank you @georgeshk . I will use your template text to create a new issue (as soon as I get to it), and close this one, so we have a clean slate to work from.
