### ISSUE TITLE
Mankind 2.0: Raising awareness of the impact of technology on our society

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#12]
# "Mankind 2.0" Campaign Theme

## Info 

- Name: **Mankind 2.0**
- General discussion: [Community forum topic](https://community.humanetech.com/t/mankind-2-0-campaign-theme-making-people-aware-how-technology-impacts-their-lives/2785)

## Summary 

Raising awareness of the impact of technology on our society by producing unsettling or jarring experiences resulting from a wide disparity between what was expected and what the real situation turns out to be.

## Topics

- Smartphone addiction
- Social media addiction
- Privacy
- Social credits
- _(More to come; all 'Harms of Technology' apply)_

## Objectives

- Shock the audience

- Lead to introspection and questioning

- Make the audience think and reach their own conclusions

- Provoke, rather than convince

## Description

This theme is based on the following principles:

- Not to push a certain agenda, or lecture the target audience
- Instead, provoke introspection and lead the audience to reach their own conclusions as to whether they are comfortable with the impact of such and such aspect of technology on their lives
- Acknowledge that we have become a very different society in a very short time and ask the question: _"Should we consider this more carefully?"_

## Strategy

- This theme does not require a high-level strategy. Strategies can be found on individual campaigns.

## Campaigns

- [Reality Shock](campaigns/reality-shock/README.mdl) - Using short, dramatic video's to shock people into awareness

## Resources

- This theme has no additional resources yet. Please edit or comment to add your relevant links.

**Comment by georgeshk** [comment]
Guys, I know we are still very few to constitute a representative segment of the community, but seems we all agree on this (unless you have any comment), plus we started with concepts falling under this theme.

Proposing to close this issue and move them description to the "Code" section. Agreed?

**Comment by aschrijver** [comment]
I agree, but first create a Pull Request (PR), and only close this issue once that PR is merged. That is the best workflow. And we could also keep it open a bit longer for discussion in case more things pop up.

**Comment by georgeshk** [comment]
Please see pull request so that we can close this issue.
