### ISSUE TITLE
Mankind 2.0 Campaign - First Video (A coffee place)

### ISSUE THREAD

**Issue by georgeshk** [humanetech-community/humanetech-community-awareness#2]
### Campaign theme

- [Reality Shock](https://github.com/humanetech-community/humanetech-community-awareness/issues/1) - The overarching theme of the campaign is to provoke and make people ponder the question: _"Are you really comfortable with this?"_

### Campaign

- Working title: [Mankind 2.0]

### Video No. 1

- Working title: [A coffee place]

**Comment by aschrijver** [comment]
I think I have a nice (working) title for the campaign / video. How do you like: **Body Snatchers**?

**Comment by georgeshk** [comment]
> I think I have a nice (working) title for the campaign / video. How do you like: Body Snatchers?

I was just writing about the campaign name on the other script, proposing "Mankind 2.0". More neutral, good blend. Body Snatchers makes sense, especially given the proposed conclusion of Video 1, however it is explicitly negative, and my thinking about the whole campaign was that we should appear as neutral as possible. We observe, but don't point in any direction (well, we obviously have our own thinking and biases, but essentially we just draw pictures and tell stories).

**Comment by patmatsu** [comment]
How about "Picture This"? Or is that too subtle or indirect?

**Comment by aschrijver** [comment]
Ah, sorry for prematurely editing. But this is the first issue, so we'll experiment with it.

> my thinking about the whole campaign was that we should appear as neutral as possible

I am not sure about that. You also wanted to create 'shocking video's' to raise awareness with young people, and have viral potential. Even though named 'Body Snatchers' the video can still end on a positive note, after the first suspense.

If I read your script you are showing people getting more and more absorbed and later on showing how tech giants extract their data from their heads (with the data overlay in the air above), etc.

**Comment by georgeshk** [comment]
## Distinction between Campaign and individual videos

I think we have a misunderstanding about what is a campaign. For me, one of the campaigns is "Reality Shock" or "Mankind 2.0", and includes all short videos that shared the common theme (see discussion in the campaign thread). The other campaign is "Phone Zombies".

## Mode of collaboration

I noticed you already made changes to the campaign name, without waiting for others to comment. Please get collaborators' approval before making changes to their own posts.

**Comment by georgeshk** [comment]
Just saw your post about working title. Sorry I missed the distinction. However, I feel we should be consistent between how we call the thing internally and externally, out of transparency.

Anyway, let us not get bogged down in discussions about codenames or such, it is not that important. But, PLEASE, do not make changes without getting consensus!

**Comment by aschrijver** [comment]
> But, PLEASE, do not make changes without getting consensus!

You are entirely correct, and this is not good Github behavior, so sorry once again. But this discussion is premature, since both the project structure, proces and information model of themes vs. campaigns is incomplete. I was trying to help. I'll not pollute this discussion with that info, but create separate issues for that :slightly_smiling_face:

**Comment by georgeshk** [comment]
Hi Arnold,

No harm done, I changed it back already. Yes, I think we have not all agreed on names, themes, campaigns definition.

For me, there are 2 campaigns right now:

- The short videos (plural) all under the name "Reality Check", which I borrowed from you
- The Phone Zombies project

These are the names we should use for now to designate the two campaigns.

Now, under "Reality Check", there are several videos (we are working on Video 1 right now). I prefer to stay neutral - on the outside - hence the name "A coffee place" for now.

Each campaign has a "Theme", as described by Borja.

On the other hand, each video has its own "Concept", which I elaborated in the file I submitted.

I hope this clarifies my thinking.

I would be happy to do more as to structuring, could you elevate my status so I can write to?

Cheers,
Georges




Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by georgeshk** [comment]
> I was thinking of Reality Shock as a theme for multiple campaigns. My Phone Zombies video idea also fits that theme. More later

So we would have a unifying theme, under which would be two campaigns (for now), each with their own nuances and variations: the short, dramatic videos I was thinking of, and the "Phone Zombies" video you had in mind. This could work! Both campaigns could share all the strategic folders structure I discussed earlier in the pull request. Under "Campaigns", we would have "Phone Zombies" and "Mankind 2.0" (let's say). 

Would that be ok with you?

**Comment by aschrijver** [comment]
Yes, this was the idea. But let's completely separate the structure stuff (I'll create a separste issue on this as soon as I have time) from your current idea (this issue). I like where you are going with it.

**Comment by georgeshk** [comment]
Proposing to close the issue as @schrijver clarified all terms in https://github.com/humanetech-community/humanetech-community-awareness/issues/6

With the theme "Reality Check", the proposed campaign name is "Mankind 2.0". I will introduce the first video ("A coffee place") of this campaign in a new issue.

**Comment by aschrijver** [comment]
Minor correction for anyone still reading this: Theme = Mankind 2.0, Campaign = Reality Shock
Thanks for bringing this to a new issue @georgeshk !
