### ISSUE TITLE
Aware Prepare: Growth hacking the Awareness Campaigns project

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#24]
# "Aware Prepare" Campaign

## Info 

- Name: **Aware Prepare**
- Theme: [Dogfooding](themes/dogfooding/README.md)
- General discussion: [This forum topic](https://community.humanetech.com/t/aware-prepare-growth-hacking-the-awareness-campaigns-project/2839)

## Summary 

Crowdsourcing means, finding a crowd of contributors. This campaign is about growth hacking the public to find as much people willing to participate, so that our campaign efforts get ever more effective.

## Goals

- Reach out to the target audience across all (social) media channels, and personal networks.

- Make people aware how they can join, and be part of the solution to their growing tech worries.

- Apply targeted recruitment tactics to find people in the roles we need for ongoing campaigns

## Audience

- Everyone that is aware of our tech problems, and willing to help address it, but doesn't know how.

## Success criteria

The success criteria will need to be updated as the project comes along, but currently are:

- Demonstrate there is a large body of people out there that are ready to be activated
- Find the right people in the appropriate roles needed to execute our first campaigns with success

## Retrospective

- No retrospective has been held yet.
- Retrospectives will be held in quick success to adopt lessons-learned asap.

## Description

The awareness campaigns that are defined in this project are complex beasts. They need lots of skills, coordination and activity by many contributors. A single campaign can only succeed if there are enough of the right people willing to spend their time on it. Likewise, the more contributors we find, the more campaigns that we can work on in parallel.

So the first part of this campaign involves the community building and growth hacking that is required to get more people on board.

The second - and even more important - part, constitutes of improving the onboarding process, so that:

- People feel directly at home, and can inform themselves on how best to start contributing.
- New members become active in this campaign and help with the growth hacking of the project.

### Documentation: [Project Guide](deliverable-url) 

As we go along, and more members join, we learn from the questions they ask us, and the problems they have. This experience is used to improve both the project structure and workflows and documenting them in this Project Guide.

This way we'll have to spend ever less time with the 'boring stuff' and more on reaching the public in exciting campaigns.

### Activity: [We Need You](deliverable2-url)

This is an application of the [Turning the weapon around](https://community.humanetech.com/t/idea-turning-the-weapon-around-raising-awareness/423) idea on the forum, a ongoing activity, where project members reinforce each other's social media promotion, by adding their own Likes, Shares, and add Comments.

The added reward for participants in this activity is, that they can become more influential in their own social media channel, e.g. on LinkedIn, and develop their reputation.

### Documentation: [Growth Hacking Guide](deliverable2-url)

As part of the _We Need You_ activity we will frequently update a Growth Hacking Guide with our lessons-learned - adding the things that worked best. This way others don't make the same mistakes when they first chime in to the growth hacking process, and campaign effectiveness continues to increase.

The benefits and rewards will be developing strategies that can be applied to other campaigns and developing our own social media strategic skillset.

## Strategy

- TODO Summarize strategy here, but details are in the Project and Growth Hacking guides.

## Funding

- No funding is required to execute this campaign. 

## Milestones

- Milestones should still be determined, but none are required right now

## Resources

- This theme has no additional resources. Please edit or comment to add your relevant links.

**Comment by patmatsu** [comment]
A couple of thoughts, @aschrijver:

1. People on CHT's Facebook page would be interested in helping to grow campaigns, I'm sure, but who among us is on FB?
2. MeWe is also a possible place to interest/recruit people. Should I/we create a MeWe page for HTC?

**Comment by aschrijver** [comment]
> You are looking for people to contribute ideas for campaigns as well as to help carry them out, correct?

Yes, both are part of this project and can be used in strategy to attract people to it. But contributing ideas comes secondary to being able to deliver, to execute campaigns, therefore the _Prepare_ in the name.

Anyone may contribute ideas, any CHT meber, but also non-members (like any Github users).
And both CHT's FB group and MeWe are channels we can target, include in the campaign strategy.

**Comment by georgeshk** [comment]
I would like to make what I believe is a very important point. 

Reaching out to potential contributors in a non discriminative manner (such as on various social media platforms) greatly elevates the risk we inadvertently invite trolls and disruptive participants. This is a real concern, even if one sees it as a remote possibility (to me, the possibility is quite real). If this happens, we could turn into another reddit.

I have started causally having conversations with random strangers - physically, not on the ether. Over the course of a 30-minute discussion, I can form a pretty good idea whether that person would be a valuable contributor, at which point I can then suggest him to have a look at the CHT community.

Quality, not quantity is paramount. Let us go back to building networks in the good old-fashioned way.

**Comment by aschrijver** [comment]
Yes, this a good point, and something to consider in the (campaign) strategy.

We should not wildly fire off 'Join Us' requests full-spectrum. Instead each channel requires different approaches.

And we should start small, targeted, and only fan out when we can handle the response.

I am quite sure that a 'Show HN' submit on Hacker News will be a high-value promotion.

On LinkedIn it is best to start with approaching 1st-line contact, and strategically place comments on relevant timeline articles.

We should stay away from Twitter and Instagram, and for Reddit and FB only target high-quality groups (on FB probably only the CHT group).

Some trolls will come, though. That is unavoidable (happens now already on the forum). Both forum and Github have good tools to fight them.

But in our promotion we will only refer to the forum, not Github, so that is our first line of defence.

**Comment by georgeshk** [comment]
> and for Reddit and FB only target high-quality groups

I don't know about Facebook (never used the bloody thing), but Reddit? Forget it. I tried it a few times, the vast majority of people there are psychos.

**Comment by georgeshk** [comment]
> Both forum and Github have good tools to fight them.

I certainly hope so. But it could quickly becomes very distracting to spend time analyzing whether such and such person is disturbing. It may be innocuous at first, then, when we realize it, damage is done. Counter-productive discussions leading to quality people abandoning the project.

**Comment by aschrijver** [comment]
>  But it could quickly becomes very distracting to spend time analyzing whether such and such person is disturbing.

That is what we have moderators for. Currently we have 2 active ones, including me. But we have 10 slots. I already sent 2 enquiries to inactive mods. They lose their privilege if I do not get reaction soon.
If need be, let's continue this on the forum.

**Comment by aschrijver** [comment]
We have that filter because we promote the forum, not Github. That comes later, when they are member and campaigner. Als trolling is hardly an issue on Github, I have _never_ had an issue myself and only know of 2 projects where there were issues (one the Post-Meritocracy repo and the other a super large Microsoft project). As long as things stay a-political, not-too-controversial, things should be fine.

**Comment by aschrijver** [comment]
Closing issue, continuing in [Aware Prepare](campaigns/aware-prepare/) campaign documents directly.
