### ISSUE TITLE
Phone Zombies: Absorbed by phone in social settings and in public

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#25]
# "Phone Zombies" Campaign

## Info 

- Name: **Phone Zombies**
- Theme: [Speak Easy](themes/speak-easy/README.md)
- Status: Ideation
- Original idea: @aschrijver 
- Coordinator: TBD
- General discussion: [This forum topic](https://community.humanetech.com/t/phone-zombies-campaign-anchoring-the-term-phone-zombies-in-common-language/2710)

## Summary 

This campaign focuses on "Phone Zombies", people absorbed in smartphones to the cost of all else, to make them aware of this unsocial behavior, promote smartphone self-consciousness, change habits.

## Goals

- Widespread adoption and use of the Phone Zombie language term and memes.

- Reinforce the notion that being called a Phone Zombie is something to avoid

- Others pay attention because calling someone Phone Zombie is a funny tease

## Audience

The campaign is basically targeted to the entire population, but there are 2 groups:

- Everyone that is effectively a Phone Zombie in how they use their smartphone
- Anyone that wants to tease, or call someone out as a Phone Zombie if he/she deserves it

## Success criteria

Success is hard to measure, especially with no prior experience. But we should define metrics for individual deliverables (no. of shares, likes, etc.).

- Success criteria will be more closely defined as the campaign comes along.

## Retrospective

- No retrospective has been held yet. The first retrospective is planned at [retrospective date].

## Description

Phone Zombies are people who aren't paying attention to their surroundings because they are focused upon their smartphone (see: [Wikipedia](https://en.wikipedia.org/wiki/Smartphone_zombie)). This happens in all kinds of social settings: during a one-on-one talk with a friend, or when in a group. At a brithday party. Or when walking (or cycling) on the street, where zombies bump into other pedestrians.

People are not aware how this erodes the social fabric. 'Phone Zombie' is the term to have people snap out of it, and make them feel (slightly) ashamed. When the use of the term becomes more widespread, and the ways to make people aware they are zombies, a self-consciousness will creep in, and people will try to avoid being called the Zombie yet again. This is the point where habits and behavior starts to change. And this is the ultimate goal of this campaign.

Some examples of how it is used in spoken language:

- "Hey Phone Zombie! Watch where you're going!"
- "Ohh, he has turned into a husk. A proper Phone Zombie.. Snap out of it, man!"
- "This freaking place is full of Phone Zombies. I'm outa here!"

And in social media memes:

- [Guy to his friend, pointing to other friend]: "Hey look, he's out again. Send it now!" --> Friend sends Whatsapp animated GIF to zombie friend, who automatically opens it, because that's what zombies do.
- [Friend keeps responding on FB Messenger, tiring of conversation] --> Send fiend Phone Zombie image as sign to stop 'conversation'.

### Video: [Phone Thriller](deliverable-url) (TODO) 

This very short, funny - but with shock effect - video re-enacts the start of Michael Jackson's famous Thriller until the moment that Michael is touched at the shoulder and swivels around, showing his zombie face.

### Video: [Spirited Away](deliverable2-url) (TODO)

During a social gathering with friends, there is a strange bird sound. One friend changes behavior, becomes distracted, and turns his back to the others. When he is twisted around by his peer, he has changed in a snarling, saliva-dripping (Phone) Zombie, that resists coming back to reality.

### Video: [All Alone](deliverable3-url) (TODO)

This is an adaptation of the [animated video](https://www.youtube.com/watch?v=15nR7nhFRZE) of Steve Cutts, and not dissimilar to [I Am Legend](https://en.wikipedia.org/wiki/I_Am_Legend_(film)) with Will Smith where everyone is a Phone Zombie, and there is no one to have social interactions with

### Images

A series of images depicting memes to share on social media, as well as images to use in mastheads and link previews of blog posts and articles

### GIF's

A series of animated GIF's to share on social media

## Strategy

- Campaign strategy yet to be determined. Details will be in a separate campaign strategy document.

- Additionally you can point to general strategy resources in the `/strategy` folder.

## Funding

- Funding requirements will be determined per individual Deliverable. 

## Milestones

- No milestones have been set yet.

## Resources

- This campaign has no additional resources. Please edit or comment to add your relevant links.

**Comment by georgeshk** [comment]
The whole concept and objectives are well described, and great to already have some proposals of concrete deliverables.

I propose to exchange and brainstorm on possible deliverables here in this thread until some of them reach a sufficient level of development / support, at which point detailed discussions on the execution can move to a different issue.

**Comment by georgeshk** [comment]
Just getting the ball rolling... 
![slide1](https://user-images.githubusercontent.com/43905276/46931176-a2c2d600-d07c-11e8-820a-5eecf59401b5.gif)

**Comment by aschrijver** [comment]
There is one big point of concern, regarding your example (unless you didn't add the text yourself, but you _have_ to mention image source still):

- People may not want to have their face associated with the meme (I would not)!
- We need permission before we combine

I used pictures from Ritzo ten Cate's "Lost in the App" series, who are perfect candidates. But here I even regret the association in the Zombies thread (will change this).

Note that e.g. Facebook has functionality that reports to users where their face has been used, when they turn on Facial recognition.

**Comment by georgeshk** [comment]
That one is good too (same copyright owner, can buy license)

https://previews.123rf.com/images/ostill/ostill1210/ostill121000137/15641165-caucasian-man-unshaven-looking-at-cellphone-amazed-portrait-isolated-studio-on-black-background.jpg

**Comment by aschrijver** [comment]
I moved Phone Zombie stock photography to the forum, using the watermarked preview instead (marked comment containing image as Resolved).

**Comment by aschrijver** [comment]
Updated the Campaign document, closing issue (But you can still add comments to discuss changes).
