### ISSUE TITLE
Smartphones as poor resource

### ISSUE THREAD

**Issue by patmatsu** [humanetech-community/humanetech-community-awareness#37]
# Smartphones as Poor Resource

## Info 

- Name: **Smartphones as Poor Resource**
- General discussion: Smartphones

## Summary 

This concept is based on information in Maryanne Wolf's book _Reader Come Home: The Reading Brain in a Digital World._ In households that do not have computers or tablets, the smartphone serves as the way children connect with the outside world. But it's a poor connection, one that doesn't enhance their education but steers them away from it.

## Topics

- Children's dependency on smartphones
- Digital wellbeing

## Objectives

- Create awareness of the harms of exclusive, continuous use of smartphones by children.

## Description

This is a complicated issue, requiring (1) social awareness of the underprivileged and deprived and (2) a social conscience, i.e., the desire to help lower-middle-class and poor children.

## Strategy

- This theme can be addressed in various ways, such as writing essays or articles, interviewing parents about their children's phone use, and studying households to see how education can be made a priority when resources are scarce.

## Campaigns

- [Campaign 1](campaign1-url) - Campaign 1 short description
- [Campaign 2](campaign2-url) - Campaign 2 short description

## Resources

- This theme has no additional resources yet. Please edit or comment to add your relevant links.

**Comment by aschrijver** [comment]
Hi @patmatsu You asked me to add deliverable-proposal label, but I think you actually meant Theme, and about communication issues (i.e. the  deterioration of communication skills), am I right?

I think, given that you mention children and education, it is very similar to Tech Wise, and this could fit very well in that theme. I mean 'wise with tech' also means having the awareness of how it affects the quality of communicating in 'old-fashioned' ways. Maybe you can discuss with @healthyswimmer on the forum first (e.g. [here](https://community.humanetech.com/t/tech-wise-campaign-theme-promoting-prudent-technology-use-in-child-education/2823)) and see how this matches, then one of you drafts the Tech Wise theme?

**Comment by patmatsu** [comment]
Yes, that sounds like a good idea. I did briefly think about putting this under Tech Wise, but it has a economic aspect that I wanted to bring out: the ways in which the poor or deprived suffer inordinately as a result of our society's dependence on technology. The smartphone is the calorie-rich, nutrition-empty equivalent of candy and soda. It "feeds" children but doesn't nourish them.

**Comment by patmatsu** [comment]
Do you think we could change "Tech Wise" to "Tech Rich and Tech Poor"? Would that distort the concept?

**Comment by aschrijver** [comment]
It think Tech Wise covers both knowing when it enriches you or otherwise, so I prefer sticking with that.

**Comment by aschrijver** [comment]
This issue is merged with the Tech Wise campaign theme here: https://github.com/humanetech-community/humanetech-community-awareness/issues/41
