### ISSUE TITLE
Aware Prepare: Prepare msg to CHT facebook group with Roadmap, Call to Action

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/humanetech-community-awareness#46]
See: [Aware Prepare Strategy](campaigns/aware-prepare/campaign-strategy.md#activity-planning)

After forum is updated (see strategy and #44 ) post a message to the CHT facebook group with a summary of our roadmap and plans, and a call to action for our Awareness Campaigns program.

We can prepare the message together in the Campaigners group in a wiki post.

**Comment by patmatsu** [comment]
Can you provide me with the forum link please? It seems to have disappeared.

**Comment by aschrijver** [comment]
Ah, it is this link @patmatsu : https://community.humanetech.com/t/preparing-announcement-to-the-cht-facebook-group/2908

**Comment by aschrijver** [comment]
I did not get to preparing the text for the new pinned forum messages. I want to present some kind of community roadmap in that.

**Comment by aschrijver** [comment]
What URL did you put that on, Pat?

**Comment by patmatsu** [comment]
https://community.humanetech.com/t/preparing-announcement-to-the-cht-facebook-group/2908/8

I edited the wiki post.

**Comment by aschrijver** [comment]
Done. Thanks @patmatsu !
