### ISSUE TITLE
Write an introductory text

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/humanetech-community-awareness#80]
Write a few sentences for the introduction, something that would begin like this:

>Welcome to the podcast series of the Humane Technology Community, an online forum of…

We could use some of the text we developed for the Mozilla sprint event.

**Comment by micheleminno** [comment]
HTC aims to be the reference point - gathering people and partners worldwide - for creative awareness campaigns about the harms of addictive and harmful technologies, and - most of all - proposing and guiding to systemic and technological solutions, coming with a humane purpose and design, aligned with our own needs and long term aspirations, evaluated by us for what they bring into our lives.

**Comment by micheleminno** [comment]
What do you think @patmatsu ?

**Comment by patmatsu** [comment]
Mic, I recorded this a couple times and started to change a few things here and there. What do you think of this text:

HTC aims to be the reference point - gathering people and partners worldwide - for creative awareness campaigns about the harms of addictive and invasive technologies. HTC proposes to guide people to systemic and technological solutions, starting with a humane purpose and design. We evaluate technology for what it brings into our lives—how it supports our long-term needs and aspirations. This podcast series is part of that effort.

**Comment by patmatsu** [comment]
Here is the text that should appear on the webpage for the podcast; please feel free to edit as you see fit. Thanks for all your help, Mic.

---

**Summary**

The first in a series, this podcast covers free, libre, open-source software (FLOSS) and the creation of browser addons to improve user security and privacy. Among the humane-tech principles discussed are the following: 

- The FLOSS movement expands and strengthens human rights, among them the right to knowledge and transparency.
- Sharing code (under freedom-respecting licenses) is a global educational endeavour
- HTC is itself an example of working and leading in the open.

**Participants**

- Questioner: Pat Matsueda ([Twitter](https://twitter.com/patmatsueda))
- Developer: Gokulakrishna Sudharsan ([Twitter](https://twitter.com/gkrishnaks), [Mastodon](https://framapiaf.org/@gkrishnaks))

**Questions**

- Could you please explain, in layperson’s terms, what free, libre, open-source software is?
- What kinds of licenses does FOSS use?
- Please describe the three addons you created for Firefox.
- HTC has what it calls an awesome humane tech list: open-source software that it recommends for use by members. Could you talk about this list?
- Dion Moult, writing on what he calls ethical software, said: “Software should be created by the community. That is, not only open-source, but the core developers should be welcoming to all contributors and unafraid of forks”. Please define “forks” and explain why users should be able to create them.
- For those users who don’t have tech backgrounds, what fundamental principles of software use and internet behaviour would you recommend?

**Projects discussed**

- [Wayback Everywhere](https://addons.mozilla.org/en-US/firefox/addon/wayback-everywhere) (for installing in other browsers, see [here](https://gitlab.com/gkrishnaks/WaybackEverywhere-Firefox/snippets/1739885))
- [Cloud Firewall](https://addons.mozilla.org/en-US/firefox/addon/cloud-firewall)
- [Warn Common Password](https://addons.mozilla.org/en-US/firefox/addon/warn-common-password)

**References for topics**

- [Thoughts on why Wayback Everywhere addon is needed](https://gitlab.com/gkrishnaks/WaybackEverywhere-Firefox/snippets/1799237)
- [Awesome Humane Technologies list](https://github.com/humanetech-community/awesome-humane-tech/blob/master/README.md)
- [Tool that estimates the cost and effort of FLOSS projects](https://www.openhub.net)
- [Estimated cost/effort analysis for Wayback Everywhere addon](https://www.openhub.net/p/WaybackEverywhere/estimated_cost)
- [Estimated cost/effort analysis for Cloud Firewall addon](https://www.openhub.net/p/cloud-firewall/estimated_cost)
- [Free Software Foundation](https://fsf.org)
- [What is free software (free as in freedom, not cost)](https://www.gnu.org/philosophy/free-sw.en.html)
- [How free software is essential for educational purposes at schools/ universities](https://www.gnu.org/education/education.html)
- [Free software’s importance greater today than in the past](https://www.gnu.org/philosophy/free-software-even-more-important.html)
- [Kashmir Hill](https://twitter.com/kashhill), research journalist
- [Kashmir Hill’s research series _Life Without the Tech Giants_](https://gizmodo.com/life-without-the-tech-giants-1830258056) (Gokul states that this research series inspired him to build the Cloud Firewall addon, which enables everyone to replicate Kashmir’s research)
- [Ublock Origin addon](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin)
- [Common passwords research](https://github.com/berzerk0/Probable-Wordlists) - [researcher](https://berzerk0.github.io/GitPage/about/about-index.html) who conducted this research

**Comment by patmatsu** [comment]
Very happy with how this looks. Thanks, Mic!

**Comment by patmatsu** [comment]
Transcript is coming along. Finished 8" and have about 13" left.

**Comment by micheleminno** [comment]
**Summary**

Though this discussion appears to be about a technical matter, it is much more than that. In the course of talking about FLOSS and his three addons, Gokul makes these ethical-philosophical points:

* the free software (FLOSS) movement expands and strengthens human rights, among them the right to knowledge and transparency
* sharing code (under freedom-respecting licenses) is a global educational endeavor
* HTC is itself an example of working and leading in the open.

**Comment by patmatsu** [comment]
**Summary**

Though this discussion appears to be about a technical matter, it is much more than that. In the course of talking about FLOSS and his three addons, Gokul makes these ethical-philosophical points:

* the free software (FLOSS) movement expands and strengthens human rights, among them the right to knowledge and transparency
* sharing code (under freedom-respecting licenses) is a global educational endeavor
* HTC is itself an example of working and leading in the open.

**Participants**
Gokulakrishna: https://twitter.com/gkrishnaks •  https://framapiaf.org/@gkrishnaks (mastodon)
Pat: https://twitter.com/patmatsueda

**Questions** 

* Could you please explain, in layperson’s terms, what free, libre, open-source software is?

* What kinds of licenses does FOSS use?

* Please describe the three addons you created for Firefox.

* HTC has what it calls an awesome humane tech list: open-source software that it recommends for use by members. Could you talk about this list?

* Dion Moult, writing on what he calls ethical software, said, “software should be created by the community. That is, not only open-source, but the core developers should be welcoming to all contributors and unafraid of forks.” Please define “forks” and explain why users should be able to create them.

* For those users who don’t have tech backgrounds, what fundamental principles of software use and internet behavior would you recommend?

**Projects discussed**
* Wayback Everywhere https://addons.mozilla.org/en-US/firefox/addon/wayback-everywhere/ 
For installing in other browsers, see https://gitlab.com/gkrishnaks/WaybackEverywhere-Firefox/snippets/1739885  
* Cloud Firewall https://addons.mozilla.org/en-US/firefox/addon/cloud-firewall/
* Warn Common Password https://addons.mozilla.org/en-US/firefox/addon/warn-common-password/

**References for topics**
* Thoughts on why Wayback Everywhere addon is needed: https://gitlab.com/gkrishnaks/WaybackEverywhere-Firefox/snippets/1799237
* Awesome Humane Technologies list: https://github.com/humanetech-community/awesome-humane-tech/blob/master/README.md
* Tool that estimates the cost and effort of FLOSS projects: https://www.openhub.net/
* Estimated cost/effort analysis for Wayback Everywhere addon: https://www.openhub.net/p/WaybackEverywhere/estimated_cost
* Estimated cost/effort analysis for Cloud Firewall addon: https://www.openhub.net/p/cloud-firewall/estimated_cost
* Free Software Foundation: https://fsf.org
* What is free software (*free* as in *freedom,* not cost): https://www.gnu.org/philosophy/free-sw.en.html 
* How free software is essential for educational purposes at schools/ universities: https://www.gnu.org/education/education.html 
* Free software's importance greater today than in the past: https://www.gnu.org/philosophy/free-software-even-more-important.html
* Kashmir Hill, research journalist: https://twitter.com/kashhill
* Kashmir Hill's research series "Life Without the Tech Giants": https://gizmodo.com/life-without-the-tech-giants-1830258056 (Gokul states that this research series inspired him to build the Cloud Firewall addon, which enables everyone to replicate Kashmir's research)
* Ublock Origin addon: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
* Common passwords research: https://github.com/berzerk0/Probable-Wordlists (profile of the researcher who conducted this research is at https://berzerk0.github.io/GitPage/about/about-index.html) 
* Dion Moult on forking https://thinkmoult.com/five-fundamental-facets-of-ethical-software.html

**Comment by patmatsu** [comment]
Gokul asked that this be added to the list of references:

Dion Moult on forking https://thinkmoult.com/five-fundamental-facets-of-ethical-software.html
