### ISSUE TITLE
Crowdfunding / other financing options

### ISSUE THREAD

**Issue by ghost** [humanetech-community/humanetech-community-awareness#9]
Producing high-quality videos with maximal spread and impact potential will require commissioning professional video producers. While we should and will try to secure advantageous terms or even a free deal (not unusual for producers to work pro bono if they believe in the project's potential), it is quite likely we will have to incur costs.

Hence the question: "How to raise the funds?"

Crowdfunding may be an option, but this may prove difficult (We want to raise awareness through our projects, but to finance our projects, we need not only to raise awareness in the first place, but secure donations...). Rewards for donators may include sending a free gift item, crediting them at the end of the respective video, etc. These are just some ideas.

We would need to find the most promising crowdfunding platforms that fit our purposes, and where we won't be one of a million other initiatives. We would also need to spread the word in a viral form first through our friends and contacts.

Donations from sponsors may be another option, but we have to stay clear of associating with organizations whose objectives, practices or reputations go against the CHT's own.

Any other option?

Please all share your views on this subject here.

**Comment by georgeshk** [comment]
About sponsors: I see a lot of movies sponsored by "The National Lottery", or the lot. Worth exploring.

**Comment by georgeshk** [comment]
Guys, may I ask your views on this important topic. Unless we want to give up on a very powerful video campaign, we will likely need to work on this.

@borja (his handle on CHT forum) has promised he will soon share his unique experience trying to crowdfund his video project (which involves quite a bit of traveling costs). Until then, please let us all do our own bit of research, i.e. what crowdfunding platform out there are best-suited for the CHT (e.g. similar projects, better prospects to be successful getting donations). Second subject for brainstorming, what do we offer our donors? A limited edition free T-shirt (e.g. "Project member - "Mankind 2.0 campaign"), credits at the end of the video, any other idea?

**Comment by aschrijver** [comment]
> Premature question maybe

The whole 'crowdfunding-by-community' issue indeed requires a lot of attention, and organization. That was one of the reasons I was holding back on moving too fast on it, and my reason to draft the roadmap with unofficial and official contributors (so, that if you want to move fast, you can as unofficial initiative).

My big preference is to go easy on this, take the time, and do first do 'practice campaigns; that do not require funding (i.e. that can be fully crowdsourced by volunteers)
